### ISSUE TITLE
testbench 

### ISSUE THREAD

**Issue by ai1xian1** [Gourav0486/AES-Core-engine-#2]
Can i know how to write the testbench ?

**Comment by Gourav0486** [comment]
`timescale 1ns / 1ps

module AES_top;
    reg clk_tb;
    reg [127:0] data_in_tb,key_tb;
	reg [127:0] keyout1,keyout2,keyout3,keyout4,keyout5,keyout6,keyout7,keyout8,keyout9,keyout10;
	wire [127:0] r1_out,r2_out,r3_out,r4_out,r5_out,r6_out,r7_out,r8_out,r9_out;

    wire [127:0] data_out_tb,r0_out;

 aescipher a1(.clk(clk_tb),.datain(data_in_tb),.key(key_tb),.keyout1(keyout1),.keyout2(keyout2),.keyout3(keyout3),.keyout4(keyout4),.keyout5(keyout5),.keyout6(keyout6),.keyout7(keyout7),.keyout8(keyout8),.keyout9(keyout9),.keyout10(keyout10),.r1_out(r1_out),.r2_out(r2_out),.r3_out(r3_out),.r4_out(r4_out),.r5_out(r5_out),.r6_out(r6_out),.r7_out(r7_out),.r8_out(r8_out),.r9_out(r9_out),.dataout(data_out_tb),.r0_out(r0_out));

    

always 
begin
    clk_tb = 1'b1; 
    #20; // high for 20 * timescale = 20 ns

    clk_tb = 1'b0;
    #20; // low for 20 * timescale = 20 ns
end

initial begin
 data_in_tb = 128'h 0000_0000_0000_0000_0000_0000_0000_abc1;
 key_tb     = 128'h 1a0c_24f2_8754_95bc_b708_0e43_920f_5671;
#3000 $finish;

end


initial begin
  $dumpfile("AES_top.vcd");
  $dumpvars(0,AES_top);
    
           end

endmodule

**Comment by Gourav0486** [comment]
its a testbench i used for a different AES , i m  sure it gives you a better idea .so just change the i/p and o/P accord.

**Comment by ai1xian1** [comment]
module AES_top;
reg clk_tb;
reg [127:0] data_in_tb,key_tb;

wire [127:0] data_out_tb;

aes_main a1(.clk(clk_tb),.data_in(data_in_tb),.key(key_tb),.data_out(data_out_tb));

always
begin
clk_tb = 1'b1;
#20; // high for 20 * timescale = 20 ns

clk_tb = 1'b0;
#20; // low for 20 * timescale = 20 ns
end

initial begin
data_in_tb = 128'h 0000_0000_0000_0000_0000_0000_0000_abc1;
key_tb = 128'h 1a0c_24f2_8754_95bc_b708_0e43_920f_5671;
#3000 $finish;

end

initial begin
$dumpfile("AES_top.vcd");
$dumpvars(0,AES_top);

       end

endmodule

**Comment by ai1xian1** [comment]
But I already change it , still cannot get the data_out_tb , why ?

**Comment by KingArtur01** [comment]
> 



> Can i know how to write the testbench ?
Can i know how to write the testbench ? you have written a testbench, you have a testbench? And I can't find testbench.

**Comment by KingArtur01** [comment]
> Can i know how to write the testbench ?
